import { logger } from "./logger";

/**
 * Execution metrics captured for a single LLM invocation.
 *
 * Used to identify expensive nodes, monitor latency, and estimate
 * operational cost of interview generation workflows.
 */
export interface NodeMetric {
  /** Human-readable identifier for the node that initiated this call. */
  node: string;
  /** Total wall-clock execution time in milliseconds. */
  durationMs: number;
  /** Input/prompt tokens sent to the model. */
  inputTokens: number;
  /** DeepSeek prompt cache hits — reduces billed input cost. */
  cachedTokens: number;
  /** Output/completion tokens generated by the model. */
  outputTokens: number;
  /** DeepSeek V4-Pro / R1 chain-of-thought tokens — billed as output. */
  reasoningTokens: number;
  /** Total tokens consumed (inputTokens + outputTokens). */
  totalTokens: number;
}

interface SessionAccumulator {
  calls: NodeMetric[];
  totalInputTokens: number;
  totalCachedTokens: number;
  totalOutputTokens: number;
  totalReasoningTokens: number;
  totalTokens: number;
  totalDurationMs: number;
}

const session: SessionAccumulator = {
  calls: [],
  totalInputTokens: 0,
  totalCachedTokens: 0,
  totalOutputTokens: 0,
  totalReasoningTokens: 0,
  totalTokens: 0,
  totalDurationMs: 0,
};

function accumulateMetric(metric: NodeMetric) {
  session.calls.push(metric);
  session.totalInputTokens += metric.inputTokens;
  session.totalCachedTokens += metric.cachedTokens;
  session.totalOutputTokens += metric.outputTokens;
  session.totalReasoningTokens += metric.reasoningTokens;
  session.totalTokens += metric.totalTokens;
  session.totalDurationMs += metric.durationMs;
}

/**
 * Invokes a LangChain chat model and captures per-node execution metrics.
 *
 * Captures duration, input/output/cached/reasoning tokens. Token source
 * priority: LangChain's normalized `usage_metadata`, falling back to
 * `response_metadata.tokenUsage` for older providers.
 *
 * @param node    Human-readable identifier for this call (used in logs/tables).
 * @param model   Any LangChain-compatible chat model.
 * @param prompt  Prompt string to send to the model.
 */
export async function invokeWithMetrics(
  node: string,
  model: {
    invoke: (prompt: string) => Promise<{
      content: unknown;
      usage_metadata?: {
        input_tokens?: number;
        output_tokens?: number;
        input_token_details?: { cache_read?: number };
        output_token_details?: { reasoning?: number };
      };
    }>;
  },
  prompt: string,
) {
  const log = logger.child({ node });
  log.info("LLM invocation started");
  const start = Date.now();

  let result: Awaited<ReturnType<typeof model.invoke>>;
  try {
    result = await model.invoke(prompt);
  } catch (err) {
    const error = err instanceof Error ? err : new Error(String(err));
    log.error("LLM invocation failed", { err: error.message, stack: error.stack });
    throw error;
  }

  const durationMs = Date.now() - start;

  const usage = result.usage_metadata ?? {};
  const metric: NodeMetric = {
    node,
    durationMs,
    inputTokens: usage.input_tokens ?? 0,
    cachedTokens: usage.input_token_details?.cache_read ?? 0,
    outputTokens: usage.output_tokens ?? 0,
    reasoningTokens: usage.output_token_details?.reasoning ?? 0,
    totalTokens: (usage.input_tokens ?? 0) + (usage.output_tokens ?? 0),
  };

  log.info("LLM invocation completed", {
    durationMs,
    inputTokens: metric.inputTokens,
    cachedTokens: metric.cachedTokens,
    outputTokens: metric.outputTokens,
    reasoningTokens: metric.reasoningTokens,
    totalTokens: metric.totalTokens,
  });

  accumulateMetric(metric);

  return { result, metric };
}

/** Logs an aggregated token/cost summary for the current session. */
export function printSessionSummary() {
  const billableInput = session.totalInputTokens - session.totalCachedTokens;

  const byNode = session.calls.reduce(
    (acc, c) => {
      if (!acc[c.node]) acc[c.node] = { calls: 0, totalTokens: 0, durationMs: 0 };
      acc[c.node].calls += 1;
      acc[c.node].totalTokens += c.totalTokens;
      acc[c.node].durationMs += c.durationMs;
      return acc;
    },
    {} as Record<string, { calls: number; totalTokens: number; durationMs: number }>,
  );

  logger.info("Session token summary", {
    totalCalls: session.calls.length,
    totalDurationMs: session.totalDurationMs,
    totalInputTokens: session.totalInputTokens,
    cachedTokens: session.totalCachedTokens,
    billableInputTokens: billableInput,
    totalOutputTokens: session.totalOutputTokens,
    reasoningTokens: session.totalReasoningTokens,
    totalTokens: session.totalTokens,
    byNode,
  });
}
