/**
 * Execution metrics captured for a single LLM invocation.
 *
 * Used to identify expensive nodes, monitor latency, and estimate
 * operational cost of interview generation workflows.
 */
export interface NodeMetric {
  /** Human-readable identifier for the node that initiated this call. */
  node: string;
  /** Total wall-clock execution time in milliseconds. */
  durationMs: number;
  /** Input/prompt tokens sent to the model. */
  inputTokens: number;
  /** DeepSeek prompt cache hits — reduces billed input cost. */
  cachedTokens: number;
  /** Output/completion tokens generated by the model. */
  outputTokens: number;
  /** DeepSeek V4-Pro / R1 chain-of-thought tokens — billed as output. */
  reasoningTokens: number;
  /** Total tokens consumed (inputTokens + outputTokens). */
  totalTokens: number;
}

interface SessionAccumulator {
  calls: NodeMetric[];
  totalInputTokens: number;
  totalCachedTokens: number;
  totalOutputTokens: number;
  totalReasoningTokens: number;
  totalTokens: number;
  totalDurationMs: number;
}

const session: SessionAccumulator = {
  calls: [],
  totalInputTokens: 0,
  totalCachedTokens: 0,
  totalOutputTokens: 0,
  totalReasoningTokens: 0,
  totalTokens: 0,
  totalDurationMs: 0,
};

function accumulateMetric(metric: NodeMetric) {
  session.calls.push(metric);
  session.totalInputTokens += metric.inputTokens;
  session.totalCachedTokens += metric.cachedTokens;
  session.totalOutputTokens += metric.outputTokens;
  session.totalReasoningTokens += metric.reasoningTokens;
  session.totalTokens += metric.totalTokens;
  session.totalDurationMs += metric.durationMs;
}

/**
 * Invokes a LangChain chat model and captures per-node execution metrics.
 *
 * Captures duration, input/output/cached/reasoning tokens. Token source
 * priority: LangChain's normalized `usage_metadata`, falling back to
 * `response_metadata.tokenUsage` for older providers.
 *
 * @param node    Human-readable identifier for this call (used in logs/tables).
 * @param model   Any LangChain-compatible chat model.
 * @param prompt  Prompt string to send to the model.
 */
export async function invokeWithMetrics(
  node: string,
  model: {
    invoke: (prompt: string) => Promise<{
      content: unknown;
      usage_metadata?: {
        input_tokens?: number;
        output_tokens?: number;
        input_token_details?: { cache_read?: number };
        output_token_details?: { reasoning?: number };
      };
    }>;
  },
  prompt: string,
) {
  console.log(`Invoked: ${node}`);
  const start = Date.now();
  const result = await model.invoke(prompt);
  const durationMs = Date.now() - start;

  const usage = result.usage_metadata ?? {};
  const metric: NodeMetric = {
    node,
    durationMs,
    inputTokens: usage.input_tokens ?? 0,
    cachedTokens: usage.input_token_details?.cache_read ?? 0,
    outputTokens: usage.output_tokens ?? 0,
    reasoningTokens: usage.output_token_details?.reasoning ?? 0,
    totalTokens: (usage.input_tokens ?? 0) + (usage.output_tokens ?? 0),
  };

  console.table([metric]);
  accumulateMetric(metric);

  return { result, metric };
}

/** Prints an aggregated token/cost summary for the current session to stdout. */
export function printSessionSummary() {
  const billableInput = session.totalInputTokens - session.totalCachedTokens;

  console.log("\n╔══════════════════════════════════════════════╗");
  console.log("║           SESSION TOKEN SUMMARY              ║");
  console.log("╠══════════════════════════════════════════════╣");
  console.log(`║  Total LLM calls      : ${String(session.calls.length).padEnd(20)}║`);
  console.log(`║  Total duration       : ${(session.totalDurationMs / 1000).toFixed(1).padEnd(19)}s ║`);
  console.log("╠══════════════════════════════════════════════╣");
  console.log(`║  Input tokens         : ${String(session.totalInputTokens).padEnd(20)}║`);
  console.log(`║    └─ cached          : ${String(session.totalCachedTokens).padEnd(20)}║`);
  console.log(`║    └─ billable input  : ${String(billableInput).padEnd(20)}║`);
  console.log(`║  Output tokens        : ${String(session.totalOutputTokens).padEnd(20)}║`);
  console.log(`║    └─ reasoning       : ${String(session.totalReasoningTokens).padEnd(20)}║`);
  console.log(`║  Total tokens         : ${String(session.totalTokens).padEnd(20)}║`);
  console.log("╠══════════════════════════════════════════════╣");

  const byNode = session.calls.reduce(
    (acc, c) => {
      if (!acc[c.node]) acc[c.node] = { calls: 0, totalTokens: 0, durationMs: 0 };
      acc[c.node].calls += 1;
      acc[c.node].totalTokens += c.totalTokens;
      acc[c.node].durationMs += c.durationMs;
      return acc;
    },
    {} as Record<string, { calls: number; totalTokens: number; durationMs: number }>,
  );

  console.log("║  Per-node breakdown:                         ║");
  for (const [node, stats] of Object.entries(byNode)) {
    const label = `${node} (×${stats.calls})`.padEnd(28);
    const tokens = String(stats.totalTokens).padEnd(8);
    const secs = `${(stats.durationMs / 1000).toFixed(1)}s`.padEnd(6);
    console.log(`║    ${label} ${tokens} ${secs}  ║`);
  }

  console.log("╚══════════════════════════════════════════════╝\n");
}
