import { Phase, QuestionConfig } from "./src/graph/state";
import { BaseMessage } from "@langchain/core/messages";

/**
 * Extracts a JSON object from an LLM response.
 *
 * Handles common formatting artifacts produced by models:
 * - Removes <think>...</think> reasoning blocks
 * - Removes markdown code fences (```json ... ```)
 * - Extracts the outermost JSON object if additional prose exists
 *
 * This makes parsing more resilient to minor formatting mistakes
 * without requiring a retry.
 *
 * @param raw Raw model response
 * @returns Clean JSON string ready for JSON.parse()
 */
export const extractJson = (raw: string): string => {
  let text = raw.trim();

  // Strip <think>...</think> blocks some reasoning-distilled models emit
  text = text.replace(/<think>[\s\S]*?<\/think>/gi, "").trim();

  // Strip ```json ... ``` or ``` ... ``` fences
  const fenceMatch = text.match(/```(?:json)?\s*([\s\S]*?)```/i);
  if (fenceMatch) {
    text = fenceMatch[1].trim();
  }

  // If there's still leading/trailing prose, grab the outermost {...}
  const firstBrace = text.indexOf("{");
  const lastBrace = text.lastIndexOf("}");
  if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
    text = text.slice(firstBrace, lastBrace + 1);
  }

  return text;
};

/**
 * Removes any <think>...</think> blocks from model output.
 *
 * Useful when chaining multiple LLM calls and you want subsequent
 * prompts to consume only the visible analysis rather than internal
 * reasoning traces.
 *
 * @param raw Raw model response
 * @returns Response with all think blocks removed
 */
export const stripThinkTags = (raw: string): string => {
  return raw.replace(/<think>[\s\S]*?<\/think>/gi, "").trim();
};

/**
 * Converts free-form text into a normalized slug suitable for use
 * as a checklist key.
 *
 * Example:
 * "What are the expected traffic patterns?"
 * ->
 * "what_are_the_expected_traffic_patterns"
 *
 * @param text Source text
 * @returns Lowercase underscore-separated slug
 */
export const slugify = (text: string): string =>
  text
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, "")
    .trim()
    .split(/\s+/)
    .join("_");

/**
 * Builds the interview coverage checklist from a generated question.
 *
 * Checklist items are namespaced by interview phase:
 * - req:*    Requirements gathering topics
 * - design:* High-level design topics
 * - deep:*   Deep-dive discussion topics
 * - scale:*  Generic scalability evaluation topics
 *
 * All entries are initialized to false and updated as the
 * interview progresses.
 *
 * @param question Generated interview question configuration
 * @returns Coverage checklist keyed by phase-prefixed identifiers
 */
export const buildChecklist = (
  question: QuestionConfig,
): Record<string, boolean> => {
  const checklist: Record<string, boolean> = {};

  for (const item of question.expectedClarifications) {
    checklist[`req:${slugify(item)}`] = false;
  }

  for (const item of question.keyComponents) {
    checklist[`design:${slugify(item)}`] = false;
  }

  for (const item of question.deepDiveTargets) {
    checklist[`deep:${slugify(item)}`] = false;
  }

  // Generic scale-phase items — same across all questions
  checklist["scale:identified_bottleneck"] = false;
  checklist["scale:proposed_mitigation"] = false;
  checklist["scale:discussed_tradeoff"] = false;
  checklist["scale:back_of_envelope"] = false;

  return checklist;
};

/**
 * Creates an empty notes object for all interview phases.
 *
 * Notes are accumulated during the interview and used for
 * phase transitions, summaries, and evaluation.
 *
 * @returns Empty phase notes keyed by phase name
 */
export const emptyPhaseNotes = (): Record<Phase, string> => ({
  requirements: "",
  design: "",
  deep_dive: "",
  scale: "",
});



/**
 * Execution metrics captured for a single LLM invocation.
 *
 * Used to identify expensive nodes, monitor latency, and estimate
 * operational cost of interview generation workflows.
 */
export interface NodeMetric {
  /**
   * Name of the node that initiated the model call.
   */
  node: string;

  /**
   * Total execution time in milliseconds.
   */
  durationMs: number;

  /**
   * Number of input/prompt tokens sent to the model.
   */
  inputTokens: number;

  /**
   * Number of output/completion tokens generated by the model.
   */
  outputTokens: number;

  /**
   * Total tokens consumed by the request.
   * Typically inputTokens + outputTokens.
   */
  totalTokens: number;
}

/**
 * Invokes an LLM and captures execution metrics for observability.
 *
 * Useful for tracking token consumption, latency, and cost on a
 * per-node basis within a LangGraph workflow.
 *
 * The helper normalizes usage metadata across providers and returns
 * both the raw model response and a structured metrics object.
 *
 * Example:
 * ```ts
 * const { result, metric } = await invokeWithMetrics(
 *   "question_generator",
 *   reasoningModel,
 *   prompt
 * );
 *
 * console.log(metric.totalTokens);
 * ```
 *
 * @param nodeName Human-readable identifier for the calling node
 *                 (e.g. "stage_1_generate_question").
 * @param model LangChain chat model instance.
 * @param prompt Prompt string to send to the model.
 *
 * @returns Object containing:
 * - `result`: Raw model response returned by LangChain.
 * - `metric`: Normalized execution metrics including duration and token usage.
 */
export async function invokeWithMetrics(
  nodeName: string,
  model: any,
  prompt: string
) {
  const started = performance.now();

  const result = await model.invoke(prompt);

  const usage =
    result.usage_metadata ??
    result.response_metadata?.tokenUsage ??
    {};

  const metric: NodeMetric = {
    node: nodeName,
    durationMs: Math.round(performance.now() - started),
    inputTokens:
      usage.input_tokens ??
      usage.prompt_tokens ??
      0,
    outputTokens:
      usage.output_tokens ??
      usage.completion_tokens ??
      0,
    totalTokens:
      usage.total_tokens ??
      0,
  };

  console.log(metric);

  return {
    result,
    metric,
  };
}