import { InterviewStateType, Phase, QuestionConfig } from "./src/graph/state";
import { BaseMessage } from "@langchain/core/messages";

/**
 * Extracts a JSON object from an LLM response.
 *
 * Handles common formatting artifacts produced by models:
 * - Removes <think>...</think> reasoning blocks
 * - Removes markdown code fences (```json ... ```)
 * - Extracts the outermost JSON object if additional prose exists
 *
 * This makes parsing more resilient to minor formatting mistakes
 * without requiring a retry.
 *
 * @param raw Raw model response
 * @returns Clean JSON string ready for JSON.parse()
 */
export const extractJson = (raw: string): string => {
  let text = raw.trim();

  // Strip <think>...</think> blocks some reasoning-distilled models emit
  text = text.replace(/<think>[\s\S]*?<\/think>/gi, "").trim();

  // Strip ```json ... ``` or ``` ... ``` fences
  const fenceMatch = text.match(/```(?:json)?\s*([\s\S]*?)```/i);
  if (fenceMatch) {
    text = fenceMatch[1].trim();
  }

  // If there's still leading/trailing prose, grab the outermost {...}
  const firstBrace = text.indexOf("{");
  const lastBrace = text.lastIndexOf("}");
  if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
    text = text.slice(firstBrace, lastBrace + 1);
  }

  return text;
};




/**
 * Removes any <think>...</think> blocks from model output.
 *
 * Useful when chaining multiple LLM calls and you want subsequent
 * prompts to consume only the visible analysis rather than internal
 * reasoning traces.
 *
 * @param raw Raw model response
 * @returns Response with all think blocks removed
 */
export const stripThinkTags = (raw: string): string => {
  return raw.replace(/<think>[\s\S]*?<\/think>/gi, "").trim();
};

/**
 * Converts free-form text into a normalized slug suitable for use
 * as a checklist key.
 *
 * Example:
 * "What are the expected traffic patterns?"
 * ->
 * "what_are_the_expected_traffic_patterns"
 *
 * @param text Source text
 * @returns Lowercase underscore-separated slug
 */
export const slugify = (text: string): string =>
  text
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, "")
    .trim()
    .split(/\s+/)
    .join("_");

/**
 * Builds the interview coverage checklist from a generated question.
 *
 * Checklist items are namespaced by interview phase:
 * - req:*    Requirements gathering topics
 * - design:* High-level design topics
 * - deep:*   Deep-dive discussion topics
 * - scale:*  Generic scalability evaluation topics
 *
 * All entries are initialized to false and updated as the
 * interview progresses.
 *
 * @param question Generated interview question configuration
 * @returns Coverage checklist keyed by phase-prefixed identifiers
 */
export const buildChecklist = (
  question: QuestionConfig,
): Record<string, boolean> => {
  const checklist: Record<string, boolean> = {};

  for (const item of question.expectedClarifications) {
    checklist[`req:${slugify(item)}`] = false;
  }

  for (const item of question.keyComponents) {
    checklist[`design:${slugify(item)}`] = false;
  }

  for (const item of question.deepDiveTargets) {
    checklist[`deep:${slugify(item)}`] = false;
  }

  // Generic scale-phase items — same across all questions
  checklist["scale:identified_bottleneck"] = false;
  checklist["scale:proposed_mitigation"] = false;
  checklist["scale:discussed_tradeoff"] = false;
  checklist["scale:back_of_envelope"] = false;

  return checklist;
};

/**
 * Creates an empty notes object for all interview phases.
 *
 * Notes are accumulated during the interview and used for
 * phase transitions, summaries, and evaluation.
 *
 * @returns Empty phase notes keyed by phase name
 */
export const emptyPhaseNotes = (): Record<Phase, string> => ({
  requirements: "",
  design: "",
  deep_dive: "",
  scale: "",
});



/**
 * Execution metrics captured for a single LLM invocation.
 *
 * Used to identify expensive nodes, monitor latency, and estimate
 * operational cost of interview generation workflows.
 */
export interface NodeMetric {
  /**
   * Name of the node that initiated the model call.
   */
  node: string;

  /**
   * Total execution time in milliseconds.
   */
  durationMs: number;

  /**
   * Number of input/prompt tokens sent to the model.
   */
  inputTokens: number;

  /**
   * Number of output/completion tokens generated by the model.
   */
  outputTokens: number;

  /**
   * Total tokens consumed by the request.
   * Typically inputTokens + outputTokens.
   */
  totalTokens: number;
}

import type { BaseChatModel } from "@langchain/core/language_models/chat_models";
import type { AIMessage } from "@langchain/core/messages";

// ─────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────

export interface NodeMetric {
  node: string;
  durationMs: number;
  inputTokens: number;
  cachedTokens: number;       // DeepSeek prompt cache hits (reduces billed input cost)
  outputTokens: number;
  reasoningTokens: number;    // DeepSeek V4-Pro / R1 chain-of-thought tokens (billed as output)
  totalTokens: number;
}

/**
 * 
 * LangGraph calls this after phaseEvaluatorNode runs and uses
 * the return value to decide which node to go to next.
 * @param state 
 * @returns 
 */
export function routeAfterEvaluator(
  state: InterviewStateType,
): "interviewer" | "judge" {
  return state.interviewComplete ? "judge" : "interviewer";
}

interface SessionAccumulator {
  calls: NodeMetric[];
  totalInputTokens: number;
  totalCachedTokens: number;
  totalOutputTokens: number;
  totalReasoningTokens: number;
  totalTokens: number;
  totalDurationMs: number;
}

const session: SessionAccumulator = {
  calls: [],
  totalInputTokens: 0,
  totalCachedTokens: 0,
  totalOutputTokens: 0,
  totalReasoningTokens: 0,
  totalTokens: 0,
  totalDurationMs: 0,
};

function accumulateMetric(metric: NodeMetric) {
  session.calls.push(metric);
  session.totalInputTokens += metric.inputTokens;
  session.totalCachedTokens += metric.cachedTokens;
  session.totalOutputTokens += metric.outputTokens;
  session.totalReasoningTokens += metric.reasoningTokens;
  session.totalTokens += metric.totalTokens;
  session.totalDurationMs += metric.durationMs;
}


/**
 * Logs input and output tokens of a single interview session
 */
export function printSessionSummary() {
  const billableInput = session.totalInputTokens - session.totalCachedTokens;

  console.log("\n╔══════════════════════════════════════════════╗");
  console.log("║           SESSION TOKEN SUMMARY              ║");
  console.log("╠══════════════════════════════════════════════╣");
  console.log(`║  Total LLM calls      : ${String(session.calls.length).padEnd(20)}║`);
  console.log(`║  Total duration       : ${(session.totalDurationMs / 1000).toFixed(1).padEnd(19)}s ║`);
  console.log("╠══════════════════════════════════════════════╣");
  console.log(`║  Input tokens         : ${String(session.totalInputTokens).padEnd(20)}║`);
  console.log(`║    └─ cached          : ${String(session.totalCachedTokens).padEnd(20)}║`);
  console.log(`║    └─ billable input  : ${String(billableInput).padEnd(20)}║`);
  console.log(`║  Output tokens        : ${String(session.totalOutputTokens).padEnd(20)}║`);
  console.log(`║    └─ reasoning       : ${String(session.totalReasoningTokens).padEnd(20)}║`);
  console.log(`║  Total tokens         : ${String(session.totalTokens).padEnd(20)}║`);
  console.log("╠══════════════════════════════════════════════╣");

  // Per-node breakdown
  const byNode = session.calls.reduce((acc, c) => {
    if (!acc[c.node]) acc[c.node] = { calls: 0, totalTokens: 0, durationMs: 0 };
    acc[c.node].calls += 1;
    acc[c.node].totalTokens += c.totalTokens;
    acc[c.node].durationMs += c.durationMs;
    return acc;
  }, {} as Record<string, { calls: number; totalTokens: number; durationMs: number }>);

  console.log("║  Per-node breakdown:                         ║");
  for (const [node, stats] of Object.entries(byNode)) {
    const label = `${node} (×${stats.calls})`.padEnd(28);
    const tokens = String(stats.totalTokens).padEnd(8);
    const secs = `${(stats.durationMs / 1000).toFixed(1)}s`.padEnd(6);
    console.log(`║    ${label} ${tokens} ${secs}  ║`);
  }

  console.log("╚══════════════════════════════════════════════╝\n");
}





/**
 * Invokes a LangChain chat model and captures per-node execution metrics.
 *
 * Captures:
 * - Duration (wall-clock ms)
 * - Input tokens (total prompt tokens sent)
 * - Cached tokens (DeepSeek prompt cache hits — not billed at full rate)
 * - Output tokens (generated tokens)
 * - Reasoning tokens (DeepSeek V4-Pro / R1 thinking tokens, billed as output)
 * - Total tokens
 *
 * Token source priority: LangChain's normalized `usage_metadata` (preferred),
 * falling back to provider-specific `response_metadata.tokenUsage` for
 * older LangChain versions or providers that don't populate usage_metadata.
 *
 * @example
 * ```ts
 * const { result, metric } = await invokeWithMetrics(
 *   "stage_1_generate_question",
 *   reasoningModel,
 *   prompt,
 * );
 * // metric.reasoningTokens shows how much DeepSeek V4-Pro spent "thinking"
 * // metric.cachedTokens shows how much of the prompt was served from cache
 * ```
 *
 * @param nodeName  Human-readable identifier for this call (used in logs/tables).
 * @param model     Any LangChain BaseChatModel instance.
 * @param prompt    Prompt string to send to the model.
 */

export async function invokeWithMetrics(
  node: string,
  model: { invoke: (prompt: string) => Promise<{ content: unknown; usage_metadata?: { input_tokens?: number; output_tokens?: number; input_token_details?: { cache_read?: number }; output_token_details?: { reasoning?: number } } }> },
  prompt: string,
) {
  console.log(`Invoked: ${node}`);
  const start = Date.now();
  const result = await model.invoke(prompt);
  const durationMs = Date.now() - start;

  const usage = result.usage_metadata ?? {};
  const metric: NodeMetric = {
    node,
    durationMs,
    inputTokens: usage.input_tokens ?? 0,
    cachedTokens: usage.input_token_details?.cache_read ?? 0,
    outputTokens: usage.output_tokens ?? 0,
    reasoningTokens: usage.output_token_details?.reasoning ?? 0,
    totalTokens: (usage.input_tokens ?? 0) + (usage.output_tokens ?? 0),
  };

  console.table([metric]);
  accumulateMetric(metric);

  return { result, metric };
}