import { InterviewStateType, Phase, QuestionConfig } from "./src/graph/state";
import { BaseMessage } from "@langchain/core/messages";

/**
 * Extracts a JSON object from an LLM response.
 *
 * Handles common formatting artifacts produced by models:
 * - Removes <think>...</think> reasoning blocks
 * - Removes markdown code fences (```json ... ```)
 * - Extracts the outermost JSON object if additional prose exists
 *
 * This makes parsing more resilient to minor formatting mistakes
 * without requiring a retry.
 *
 * @param raw Raw model response
 * @returns Clean JSON string ready for JSON.parse()
 */
export const extractJson = (raw: string): string => {
  let text = raw.trim();

  // Strip <think>...</think> blocks some reasoning-distilled models emit
  text = text.replace(/<think>[\s\S]*?<\/think>/gi, "").trim();

  // Strip ```json ... ``` or ``` ... ``` fences
  const fenceMatch = text.match(/```(?:json)?\s*([\s\S]*?)```/i);
  if (fenceMatch) {
    text = fenceMatch[1].trim();
  }

  // If there's still leading/trailing prose, grab the outermost {...}
  const firstBrace = text.indexOf("{");
  const lastBrace = text.lastIndexOf("}");
  if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
    text = text.slice(firstBrace, lastBrace + 1);
  }

  return text;
};

/**
 * Removes any <think>...</think> blocks from model output.
 *
 * Useful when chaining multiple LLM calls and you want subsequent
 * prompts to consume only the visible analysis rather than internal
 * reasoning traces.
 *
 * @param raw Raw model response
 * @returns Response with all think blocks removed
 */
export const stripThinkTags = (raw: string): string => {
  return raw.replace(/<think>[\s\S]*?<\/think>/gi, "").trim();
};

/**
 * Converts free-form text into a normalized slug suitable for use
 * as a checklist key.
 *
 * Example:
 * "What are the expected traffic patterns?"
 * ->
 * "what_are_the_expected_traffic_patterns"
 *
 * @param text Source text
 * @returns Lowercase underscore-separated slug
 */
export const slugify = (text: string): string =>
  text
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, "")
    .trim()
    .split(/\s+/)
    .join("_");

/**
 * Builds the interview coverage checklist from a generated question.
 *
 * Checklist items are namespaced by interview phase:
 * - req:*    Requirements gathering topics
 * - design:* High-level design topics
 * - deep:*   Deep-dive discussion topics
 * - scale:*  Generic scalability evaluation topics
 *
 * All entries are initialized to false and updated as the
 * interview progresses.
 *
 * @param question Generated interview question configuration
 * @returns Coverage checklist keyed by phase-prefixed identifiers
 */
export const buildChecklist = (
  question: QuestionConfig,
): Record<string, boolean> => {
  const checklist: Record<string, boolean> = {};

  for (const item of question.expectedClarifications) {
    checklist[`req:${slugify(item)}`] = false;
  }

  for (const item of question.keyComponents) {
    checklist[`design:${slugify(item)}`] = false;
  }

  for (const item of question.deepDiveTargets) {
    checklist[`deep:${slugify(item)}`] = false;
  }

  // Generic scale-phase items — same across all questions
  checklist["scale:identified_bottleneck"] = false;
  checklist["scale:proposed_mitigation"] = false;
  checklist["scale:discussed_tradeoff"] = false;
  checklist["scale:back_of_envelope"] = false;

  return checklist;
};

/**
 * Creates an empty notes object for all interview phases.
 *
 * Notes are accumulated during the interview and used for
 * phase transitions, summaries, and evaluation.
 *
 * @returns Empty phase notes keyed by phase name
 */
export const emptyPhaseNotes = (): Record<Phase, string> => ({
  requirements: "",
  design: "",
  deep_dive: "",
  scale: "",
});



/**
 * Execution metrics captured for a single LLM invocation.
 *
 * Used to identify expensive nodes, monitor latency, and estimate
 * operational cost of interview generation workflows.
 */
export interface NodeMetric {
  /**
   * Name of the node that initiated the model call.
   */
  node: string;

  /**
   * Total execution time in milliseconds.
   */
  durationMs: number;

  /**
   * Number of input/prompt tokens sent to the model.
   */
  inputTokens: number;

  /**
   * Number of output/completion tokens generated by the model.
   */
  outputTokens: number;

  /**
   * Total tokens consumed by the request.
   * Typically inputTokens + outputTokens.
   */
  totalTokens: number;
}

import type { BaseChatModel } from "@langchain/core/language_models/chat_models";
import type { AIMessage } from "@langchain/core/messages";

// ─────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────

export interface NodeMetric {
  node: string;
  durationMs: number;
  inputTokens: number;
  cachedTokens: number;       // DeepSeek prompt cache hits (reduces billed input cost)
  outputTokens: number;
  reasoningTokens: number;    // DeepSeek V4-Pro / R1 chain-of-thought tokens (billed as output)
  totalTokens: number;
}

/**
 * 
 * LangGraph calls this after phaseEvaluatorNode runs and uses
 * the return value to decide which node to go to next.
 * @param state 
 * @returns 
 */
export function routeAfterEvaluator(
  state: InterviewStateType,
): "interviewer" | "judge" {
  return state.interviewComplete ? "judge" : "interviewer";
}


/**
 * Invokes a LangChain chat model and captures per-node execution metrics.
 *
 * Captures:
 * - Duration (wall-clock ms)
 * - Input tokens (total prompt tokens sent)
 * - Cached tokens (DeepSeek prompt cache hits — not billed at full rate)
 * - Output tokens (generated tokens)
 * - Reasoning tokens (DeepSeek V4-Pro / R1 thinking tokens, billed as output)
 * - Total tokens
 *
 * Token source priority: LangChain's normalized `usage_metadata` (preferred),
 * falling back to provider-specific `response_metadata.tokenUsage` for
 * older LangChain versions or providers that don't populate usage_metadata.
 *
 * @example
 * ```ts
 * const { result, metric } = await invokeWithMetrics(
 *   "stage_1_generate_question",
 *   reasoningModel,
 *   prompt,
 * );
 * // metric.reasoningTokens shows how much DeepSeek V4-Pro spent "thinking"
 * // metric.cachedTokens shows how much of the prompt was served from cache
 * ```
 *
 * @param nodeName  Human-readable identifier for this call (used in logs/tables).
 * @param model     Any LangChain BaseChatModel instance.
 * @param prompt    Prompt string to send to the model.
 */
export async function invokeWithMetrics(
  nodeName: string,
  model: BaseChatModel,
  prompt: string,
): Promise<{ result: AIMessage; metric: NodeMetric }> {
  const started = performance.now();
  const result = (await model.invoke(prompt)) as AIMessage;
  const durationMs = Math.round(performance.now() - started);

  // Prefer LangChain's normalized usage_metadata; fall back to raw provider fields
  const usage = result.usage_metadata;
  const legacyUsage =
    (result.response_metadata?.tokenUsage as Record<string, number>) ?? {};

  const inputTokens =
    usage?.input_tokens ?? legacyUsage.promptTokens ?? 0;

  const outputTokens =
    usage?.output_tokens ?? legacyUsage.completionTokens ?? 0;

  // DeepSeek-specific: cache hits live in input_token_details.cache_read
  // Anthropic uses input_token_details.cache_read too — same field
  const cachedTokens =
    (usage?.input_token_details as { cache_read?: number } | undefined)
      ?.cache_read ?? 0;

  // Reasoning models (DeepSeek V4-Pro, R1, o1, etc.) expose chain-of-thought
  // token count separately — these ARE billed as output tokens but useful
  // to track independently (high reasoning token counts = expensive Stage 1 calls)
  const reasoningTokens =
    (usage?.output_token_details as { reasoning?: number } | undefined)
      ?.reasoning ?? 0;

  const totalTokens =
    usage?.total_tokens ?? legacyUsage.totalTokens ?? inputTokens + outputTokens;

  const metric: NodeMetric = {
    node: nodeName,
    durationMs,
    inputTokens,
    cachedTokens,
    outputTokens,
    reasoningTokens,
    totalTokens,
  };

  console.table([metric]);
  return { result, metric };
}